<?php declare(strict_types=1);

/** @version 0.0.4 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<template x-if="hasCartItems">
<div id="minicart-content-wrapper">
    <div class="block-title">
        <strong>
            <span class="text"><?= __('My Cart') ?></span>
            <span
                class="qty"
                :class="qtyClass"
                title="<?= __('Items in Cart') ?>"
                x-html="cart.summary_count">0</span>
        </strong>
    </div>

    <div class="block-content">
        <button
            type="button"
            id="btn-minicart-close"
            class="action close"
            @click="closeContent"
            title="Close">
            <span>Close</span>
        </button>

        <div class="items-total">
            <span class="count" x-html="cart.summary_count">0</span>
            <span><?= __('Items in Cart') ?></span>
        </div>

        <div class="subtotal">
            <span class="label">
                <span><?= __('Cart Subtotal') ?></span>
            </span>

            <div class="amount price-container">
                <span class="price-wrapper">
                    <span class="price" x-html="cart.subtotal">-</span>
                </span>
            </div>
        </div>

        <div class="actions">
            <div class="primary">
                <button id="top-cart-btn-checkout" type="button"
                        class="action primary checkout"
                        @click="proceedToCheckout"
                        title="<?= __('Proceed to Checkout') ?>"><?= __('Proceed to Checkout') ?>
                </button>
            </div>
        </div>

        <strong class="subtitle"><?= __('Recently added item(s)') ?></strong>
        <div class="minicart-items-wrapper">
            <ol id="mini-cart" class="minicart-items">
                <template x-for="item in cart.items">
                    <li class="item product product-item odd last"
                        data-role="product-item">
                        <div class="product">
                            <a
                                tabindex="-1" class="product-item-photo"
                                :href="item.product_url"
                                :title="item.product_name">
                            <span class="product-image-container">
                            <span class="product-image-wrapper">
                            <img class="product-image-photo" loading="lazy"
                                 :src="item.product_image.src"
                                 :alt="item.product_image.alt"
                                 :width="item.product_image.width"
                                 :height="item.product_image.height">
                                         </span>
                                        </span>
                            </a>

                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a
                                       :href="item.product_url"
                                       x-html="item.product_name"
                                    ></a>
                                </strong>

                                <div class="product-item-pricing">
                                    <div class="price-container">
                                        <span class="price-wrapper" x-html="item.product_price"></span>
                                    </div>

                                    <div class="details-qty qty">
                                        <label class="label"
                                               :for="'cart-item-' + item.item_id + '-qty'"><?= __('Qty') ?></label>
                                        <input type="number" min="0" size="4"
                                               class="item-qty cart-item-qty"
                                               :id="'cart-item-' + item.item_id + '-qty'"
                                               :value="item.qty"
                                               :data-cart-item="item.item_id"
                                               :data-item-qty="item.qty"
                                               :data-cart-item-id="item.product_sku">
                                        <button  class="update-cart-item"
                                                :data-cart-item="item.item_id"
                                                @click="updateCartItemQty"
                                                title="<?= __('Update') ?>">
                                        <span><?= __('Update') ?></span>
                                        </button>
                                    </div>
                                </div>

                                <div class="product actions">
                                    <div class="primary">
                                        <a class="action edit"
                                           :href="item.configure_url"
                                           title="<?= __('Edit item') ?>">
                                        <span><?= __('Edit') ?></span>
                                        </a>
                                    </div>
                                    <div class="secondary">
                                        <a @click="removeCartItem"
                                           class="action delete"
                                           :data-cart-item="item.item_id"
                                           title="<?= __('Remove item') ?>">
                                        <span><?= __('Remove') ?></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </template>
            </ol>
        </div>

        <div class="actions">
            <div class="secondary">
                <a class="action viewcart"
                   href="<?= $block->getUrl('checkout/cart') ?>">
                    <span><?= __('View and Edit Cart') ?></span>
                </a>
            </div>
        </div>

        <div id="minicart-widgets" class="minicart-widgets">
        </div>
    </div>
</div>
</template>

<template x-if="hasNoCartItems">
    <div>
        <?= __('Your cart is empty') ?>
    </div>
</template>
