<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 0.0.7 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        const elements = [...document.querySelectorAll('[data-js-component="LumaAddToWishlist"]')];
        if (!elements.length > 0) {
            return;
        }

        elements.forEach((element) => {
            element.addEventListener('click', (e) => {
                e.preventDefault();

                const customerSection = Alpine.store('LokiLocalStorage').get('customer');
                if (!customerSection.fullname) {
                    Alpine.store('LokiMessageStore').addNoticeMessage('<?= __('You need to login to use the wishlist') ?>');
                    return;
                }

                LokiDataPost(element);
            });
        })
    });
</script>
