<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 0.0.21 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        const forms = document.querySelectorAll('[data-role="tocart-form"]');
        if (!forms) {
            return;
        }

        Object.values(forms).forEach((form) => {
            const button = form.querySelector('button[type="submit"]');
            button.disabled = false;

            form.addEventListener('submit', (e) => {
                e.preventDefault();

                button.disabled = true;

                const data = new FormData();
                data.append('product', form.querySelector('input[name="product"]').value);
                data.append('form_key', form.querySelector('input[name="form_key"]').value);
                data.append('uenc', form.querySelector('input[name="uenc"]').value);

                fetch(form.action, {
                    method: 'POST',
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest',
                    },
                    body: data
                }).finally(function () {
                    Alpine.store('LocalStorage').refresh('cart,messages', true);
                    button.disabled = false;
                });
            });
        });
    });
</script>
