<?php
declare(strict_types=1);

/** @version 0.0.7 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        const elements = [...document.querySelectorAll('[data-js-component="LumaAddToCompare"]')];
        if (!elements) {
            return;
        }

        elements.forEach(element => {
            element.addEventListener('click', (e) => {
                e.preventDefault();

                LokiDataPost(element);
            });
        })
    });
</script>
