<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 0.0.19 */
/** @var Template $block */
?>
<script>
    (function() {
        const componentElement = document.querySelector('[data-js-component="LumaLayeredNavigation"]');
        if (!componentElement) {
            return;
        }

        [...(document.getElementsByClassName('filter-options-content'))].forEach(element => {
            element.style.display = 'none';
        });

        [...(document.getElementsByClassName('filter-options-title'))].forEach(element => {
            element.addEventListener('click', function(event) {
                LokiToggle.toggleElement(
                    event.target.parentNode.querySelector('[data-role="content"]')
                );
            })
        });
    })();
</script>
