<?php
declare(strict_types=1);

/** @version 0.0.5 */

use Loki\Theme\ViewModel\FormKeyValue;
use Loki\Theme\ViewModel\StoreConfig;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var FormKeyValue $formKeyValue */

$formKeyValue = $block->getFormKeyValue();
?>
<script>
    var BASE_URL = '<?= /* @noEscape */ $block->getBaseUrl() ?>';
    var FORM_KEY = '<?= /* @noEscape */ $formKeyValue->get() ?>';
</script>
