<?php
declare(strict_types=1);

/** @version 0.0.6 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        const element = document.querySelector('[data-js-component="LumaAddToWishlist"]');
        if (!element) {
            return;
        }

        element.addEventListener('click', (e) => {
            e.preventDefault();

            const customerSection = Alpine.store('LumaLocalStorage').get('customer');
            if (!customerSection.fullname) {
                Alpine.store('LumaMessageStore').addNoticeMessage('<?= __('You need to login to use the wishlist') ?>');
                return;
            }

            const data = JSON.parse(element.getAttribute('data-post'));
            data.data.form_key = window.FORM_KEY;

            const form = document.createElement('form');
            form.method = 'POST';
            form.action = data.action;
            form.style.display = 'none';

            Object.entries(data.data).forEach(pair => {
                const key = pair[0];
                const value = pair[1];
                const field = document.createElement('input');
                field.type = 'hidden';
                field.name = key;
                field.value = value;
                form.appendChild(field);
            });

            document.body.appendChild(form);
            form.submit();
        })
    });
</script>
