<?php
declare(strict_types=1);

/** @version 0.0.8 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    (function() {
        const cookieNoticeBlock = document.getElementById('notice-cookie-block');
        if (!cookieNoticeBlock) {
            return;
        }

        const userAllowedSaveCookie = LokiCookies.isAllowedSaving();
        if (!userAllowedSaveCookie) {
            cookieNoticeBlock.style.display = 'block';
        }

        document.getElementById('btn-cookie-allow').addEventListener('click', () => {
            const lifetime = 60 * 60 * 24 * 365;
            LokiCookies.set('user_allowed_save_cookie', JSON.stringify({1:1}), lifetime);
            cookieNoticeBlock.style.display = 'none';
        });
    })();
</script>
