<?php
declare(strict_types=1);

/** @version 0.0.7 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    (() => {
        [...document.querySelectorAll('.switcher-option a')].forEach(element => {
            element.addEventListener('click', (event) => {
                event.preventDefault();
                console.log('click event', event);
                LokiDataPost(event.target);
            });
        })
    })();
</script>
