<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 0.0.9 */
/** @var Template $block */
?>
<script>
    (() => {
        [...document.querySelectorAll('.switcher-option a')].forEach(element => {
            element.addEventListener('click', (event) => {
                event.preventDefault();
                LokiDataPost(event.target);
            });
        })
    })();
</script>
