<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 0.0.8 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LumaMainMenu', () => ({
            init() {
                this.toggleSubmenus();
                this.addUiIcons();
                this.highlightSelected();
            },
            highlightSelected() {
                var item = this.$el.querySelector('a[href="' + LOKI_CURRENT_URL + '"]');
                if (item && item.parentNode) {
                    item.parentNode.classList.add('active');
                    item.parentNode.closest('li.level0').classList.add('has-active');
                }
            },
            toggleSubmenus() {
                for (level = 0; level < 3; level++) {
                    [...this.$el.querySelectorAll('li.level' + level)].forEach(element => {
                        const subMenu = element.querySelector('ul.level' + level);
                        if (subMenu) {
                            element.addEventListener('mouseenter', () => {
                                subMenu.style.display = 'block';
                            });

                            element.addEventListener('mouseleave', () => {
                                subMenu.style.display = 'none';
                            });
                        }
                    });
                }
            },
            addUiIcons() {
                [...this.$el.querySelectorAll('a')].forEach(item => {
                    const span = document.createElement("span");
                    span.classList.add('ui-menu-icon');
                    span.classList.add('ui-icon');
                    item.appendChild(span);
                });
            }
        }));
    });
</script>
