<?php
declare(strict_types=1);

/** @version 0.0.8 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$customerAccountLogoutUrl = $block->getUrl('customer/account/logout');
$customerAccountLoginUrl = $block->getUrl('customer/account/login');
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LumaTopLinks', () => ({
            init() {
                Alpine.effect(() => {
                    const customerSection = Alpine.store('LokiLocalStorage').get('customer');

                    if (customerSection.fullname) {
                        this.showCustomerUrls();
                        this.hideGuestUrls();
                        this.showGreeting();
                        this.showWishlistText();
                    } else {
                        this.hideCustomerUrls();
                        this.showGuestUrls();
                        this.hideGreeting();
                    }
                });
            },
            showCustomerUrls() {
                this.getCustomerElements().forEach(element => {
                    if (element) element.parentNode.style.display = 'inline-block';
                });
            },
            hideCustomerUrls() {
                this.getCustomerElements().forEach(element => {
                    if (element) element.parentNode.style.display = 'none';
                });
            },
            showGuestUrls() {
                this.getGuestElements().forEach(element => {
                    if (element) element.parentNode.style.display = 'inline-block';
                });
            },
            hideGuestUrls() {
                this.getGuestElements().forEach(element => {
                    if (element) element.parentNode.style.display = 'none';
                });
            },
            showGreeting() {
                const element = this.$el.querySelector('.logged-in');
                if (!element) {
                    return;
                }

                const customerSection = Alpine.store('LokiLocalStorage').get('customer');
                element.innerHTML = '<?= /* @noEscape */ __('Welcome, %1') ?>'
                    .replace('%1', customerSection.fullname);
            },
            hideGreeting() {
                const element = this.$el.querySelector('.greet.welcome');
                if (element) {
                    element.style.display = 'none';
                }
            },
            showWishlistText() {
                const element = this.$el.querySelector('.link.wishlist span.counter');
                if (!element) {
                    return;
                }

                const wishlistSection = Alpine.store('LokiLocalStorage').get('wishlist');
                if (!wishlistSection) {
                    return;
                }

                element.innerHTML = wishlistSection.counter;
            },
            getGuestElements() {
                return [
                    this.$el.querySelector('a[href="<?= /* @noEscape */ $customerAccountLoginUrl ?>"]')
                ];
            },
            getCustomerElements() {
                return [
                    this.$el.querySelector('a[href="<?= /* @noEscape */ $customerAccountLogoutUrl ?>"]')
                ];
            }
        }));
    });
</script>
