<?php
declare(strict_types=1);

/** @version 0.0.21 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        const form = document.getElementById('product_addtocart_form');
        if (!form) {
            return;
        }

        const button = form.querySelector('button[type="submit"]');
        button.disabled = false;

        form.addEventListener('submit', (e) => {
            button.disabled = true;

            e.preventDefault();

            const data = new FormData();
            form.querySelectorAll('input, select, textarea').forEach(field => {
                data.append(field.name, field.value);
            });

            fetch(form.action, {
                method: 'POST',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                },
                body: data
            }).finally(function () {
                Alpine.store('LocalStorage').refresh('cart,messages', true);
                button.disabled = false;
            });
        });
    });
</script>
